/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // SMC school brand palette used by the public scoreboard (Gold & Maroon theme).
        maroon: {
          50: '#fbf1f2',
          100: '#f3d9dc',
          300: '#c26b7c',
          500: '#7e1f31',
          600: '#6b1725',
          700: '#59121e',
          800: '#450e17',
          900: '#33090f',
        },
        gold: {
          50: '#fdf8ea',
          100: '#f7e9bd',
          300: '#eccf6c',
          400: '#e0ba3f',
          500: '#c9a227',
          600: '#a8841c',
          700: '#8a6a10',
        },
        'inverse-on-surface': '#eff1f3',
        'secondary-fixed-dim': '#b7c8e1',
        'surface-container-low': '#f2f4f6',
        tertiary: '#000000',
        'on-primary-container': '#7c839b',
        'surface-bright': '#f7f9fb',
        secondary: '#505f76',
        'tertiary-container': '#001a42',
        'on-secondary-container': '#54647a',
        'on-surface': '#191c1e',
        'tertiary-fixed-dim': '#adc6ff',
        'on-secondary': '#ffffff',
        surface: '#f7f9fb',
        outline: '#76777d',
        'outline-variant': '#c6c6cd',
        'surface-variant': '#e0e3e5',
        'secondary-fixed': '#d3e4fe',
        'primary-container': '#131b2e',
        'surface-container-highest': '#e0e3e5',
        error: '#ba1a1a',
        'inverse-primary': '#bec6e0',
        'on-background': '#191c1e',
        'secondary-container': '#d0e1fb',
        background: '#f7f9fb',
        'on-error-container': '#93000a',
        'on-primary-fixed': '#131b2e',
        'on-surface-variant': '#45464d',
        'on-secondary-fixed': '#0b1c30',
        'surface-container-lowest': '#ffffff',
        'on-secondary-fixed-variant': '#38485d',
        primary: '#000000',
        'surface-container-high': '#e6e8ea',
        'on-tertiary-fixed': '#001a42',
        'on-primary': '#ffffff',
        'surface-dim': '#d8dadc',
        'on-tertiary-fixed-variant': '#004395',
        'on-primary-fixed-variant': '#3f465c',
        'surface-tint': '#565e74',
        'surface-container': '#eceef0',
        'primary-fixed-dim': '#bec6e0',
        'inverse-surface': '#2d3133',
        'on-tertiary': '#ffffff',
        'error-container': '#ffdad6',
        'tertiary-fixed': '#d8e2ff',
        'on-tertiary-container': '#3980f4',
        'primary-fixed': '#dae2fd',
        'on-error': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        sm: '8px',
        'container-max': '1440px',
        xs: '4px',
        gutter: '24px',
        base: '4px',
        xl: '48px',
        md: '16px',
        lg: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '32px',
      },
      fontFamily: {
        'headline-lg': ['Inter'],
        'body-md': ['Inter'],
        'display-lg': ['Inter'],
        'body-lg': ['Inter'],
        'body-sm': ['Inter'],
        'mono-data': ['JetBrains Mono'],
        'label-md': ['Inter'],
        'headline-lg-mobile': ['Inter'],
        'label-sm': ['Inter'],
        'headline-sm': ['Inter'],
        'headline-md': ['Inter'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'mono-data': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
